drop table cards if exists;

create table cards (
	id bigint generated by default as identity,
	created timestamp,
	updated timestamp,
	version bigint not null,
	balance bigint,
	expiry_date date,
	pan varchar(19) not null,
	primary key (id));

alter table cards add constraint UK_unique_pan_in_card unique (pan)
