
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL

environments:
    dev:
        name: Developer Setup
    prod:
        url: http://foo.bar.com
        name: My Cool App
