
spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/spring_demo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    generate-ddl: true

jpa:
    hibernate:
      ddl-auto: update

environments:
    dev:
        url: http://dev.bar.com
        name: Developer Setup
    prod:
        url: http://foo.bar.com
        name: My Cool App
